doctrine:
    dbal:
        override_url: true
        dbname: jeromehil_digital_library_bdd
        user: jeromehil
        password: f22d7e11ba6d77d4d55e4445932dd894
        url: 'mysql://db_user:db_password@db.3wa.io:3306/db_name?serverVersion=mariadb-10.5.8'
        driver_class:         App\DBAL\MyDatabaseDriver
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
